%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: D:\zs\cu\vehicle\ovehicle_emission_1.xls
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 24-Mar-2021 11:32:16

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 61);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:BI2766";

% Specify column names and types
opts.VariableNames = ["VarName1", "SN", "Yr", "CO", "CO2", "O2", "HC", "lamda", "Age", "AFR", "Make_Honda", "Make_Mazda", "Make_MercedezB", "Make_Mitsubushi", "Make_Nissan", "Make_Peugeot", "Make_Toyota", "Make_Volkswagen", "FuelType_Petrol", "VehicleUse_Commercial", "VehicleUse_Official", "VehicleUse_Private", "Study_Failed", "Study_Passed", "OGEPA_Failed", "OGEPA_Passed", "VehicleType_BullionV", "VehicleType_Bus", "VehicleType_CABSTAR", "VehicleType_Car", "VehicleType_Jeep", "VehicleType_PICKUP", "VehicleType_TRUCK", "EUROII_Failed", "EUROII_Passed", "NESREAI_Failed", "NESREAI_Passed", "NESREAII_Failed", "NESREAII_Passed", "EUROIII_Failed", "EUROIII_Passed", "Age_0", "CO_0", "CO2_0", "O2_0", "HC_0", "Age_1", "CO_1", "CO2_1", "O2_1", "HC_1", "Age_2", "CO_2", "CO2_2", "O2_2", "HC_2", "Age_3", "CO_3", "CO2_3", "O2_3", "HC_3"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
ovehicleemission1 = readtable("D:\zs\cu\vehicle\ovehicle_emission_1.xls", opts, "UseExcel", false);


%% Clear temporary variables
clear opts

%%
T = ovehicleemission1;